name: ahl
description: A website for the community of dominican sisters at Madagascar.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
#  indicator_button:
#    git: https://github.com/Josephincrafter/indicator_button.git
  cloud_firestore: ^4.14.0
  cloud_functions: ^4.6.0
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_markdown: ^0.6.18+3
  #google_fonts: ^6.1.0
  intl: any
  json_annotation: ^4.8.1
  transparent_image: ^2.0.1
  web: any
  equatable: ^2.0.5
  formz: ^0.6.1
  markdown_widget: ^2.3.2+3
  provider: ^6.1.1
  flame: ^1.15.0
  parallax_effect: ^0.0.3
  #mouse_parallax: ^1.1.0
  #google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  mockito: any
  json_serializable: any
  build_runner: any
  fake_cloud_firestore: ^2.4.8
  firebase_storage_mocks: ^0.6.1
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/audio/
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/tiles/
    - assets/content.md
  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/butler/Butler_Regular.otf
        - asset: assets/fonts/butler/Butler_Ultra_Light.otf
          weight: 100
        - asset: assets/fonts/butler/Butler_Ultra_Light.otf
          weight: 200
        - asset: assets/fonts/butler/butler_medium.otf
          weight: 500
        - asset: assets/fonts/butler/Butler_Bold.otf
          weight: 600
        - asset: assets/fonts/butler/Butler_Black.otf
          weight: 700
        - asset: assets/fonts/butler/butler_extra_bold.otf
          weight: 800

    - family: Aileron
      fonts:
        - asset: assets/fonts/aileron/Aileron-Regular.otf
        - asset: assets/fonts/aileron/Aileron-UltraLight.otf
          weight: 100
        - asset: assets/fonts/aileron/Aileron-Thin.otf
          weight: 200
        - asset: assets/fonts/aileron/Aileron-Light.otf
          weight: 300
        - asset: assets/fonts/aileron/Aileron-SemiBold.otf
          weight: 600
        - asset: assets/fonts/aileron/Aileron-Bold.otf
          weight: 700
        - asset: assets/fonts/aileron/Aileron-Black.otf
          weight: 800
        - asset: assets/fonts/aileron/Aileron-Heavy.otf
          weight: 900

    - family: Alegreya
      fonts:
        - asset: assets/fonts/alegreya/AlegreyaSans-Regular.ttf
