name: ahl
description: A website for the community of dominican sisters at Madagascar.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.1.3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
#  indicator_button:
#    git: https://github.com/Josephincrafter/indicator_button.git
  firebase_article:
     git: https://github.com/Josephincrafter/firebase_article.git
  cloud_firestore: ^5.1.0
  # cloud_functions: ^4.6.0
  # firebase_analytics: ^10.8.0
  # firebase_auth: ^4.16.0
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_markdown: ^0.7.2
  #google_fonts: ^6.1.0
  intl: any
  json_annotation: ^4.8.1
  transparent_image: ^2.0.1
  web: any
  equatable: ^2.0.5
  formz: ^0.7.0
  markdown_widget: ^2.3.2+3
  provider: ^6.1.1
  flame: ^1.18.0
  parallax_effect: ^0.0.3
  animations: ^2.0.8
  flutter_animate: ^4.5.0
  http: ^1.1.0
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.3
  session_storage: ^0.0.1
  gap: ^3.0.1
  lottie: ^3.1.2
  #mouse_parallax: ^1.1.0
  #google_fonts: ^6.2.0
  share_plus: ^9.0.0
  dotlottie_loader: ^0.0.4
  responsive_builder: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  mockito: any
  json_serializable: any
  build_runner: any
  fake_cloud_firestore: ^3.0.1
  firebase_storage_mocks: ^0.7.0
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/content.md
    - assets/animations/
  fonts:
    - family: MyFlutterIcons
      fonts: 
        - asset: assets/fonts/flutter_icons/MyFlutterIcons.ttf
    
    - family: Butler
      fonts:
        - asset: assets/fonts/butler/Butler_Regular.otf
        - asset: assets/fonts/butler/Butler_Ultra_Light.otf
          weight: 100
        - asset: assets/fonts/butler/Butler_Ultra_Light.otf
          weight: 200
        - asset: assets/fonts/butler/butler_medium.otf
          weight: 500
        - asset: assets/fonts/butler/Butler_Bold.otf
          weight: 600
        - asset: assets/fonts/butler/Butler_Black.otf
          weight: 700
        - asset: assets/fonts/butler/butler_extra_bold.otf
          weight: 800
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900

        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

