// Mocks generated by Mockito 5.4.4 from annotations
// in ahl/test/articles/articles_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_article/firebase_article.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentSnapshot_1<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentSnapshot<T> {
  _FakeDocumentSnapshot_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArticlesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlesRepository extends _i1.Mock
    implements _i3.ArticlesRepository {
  @override
  _i2.FirebaseFirestore get firestoreInstance => (super.noSuchMethod(
        Invocation.getter(#firestoreInstance),
        returnValue: _FakeFirebaseFirestore_0(
          this,
          Invocation.getter(#firestoreInstance),
        ),
        returnValueForMissingStub: _FakeFirebaseFirestore_0(
          this,
          Invocation.getter(#firestoreInstance),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  set firestoreInstance(_i2.FirebaseFirestore? _firestoreInstance) =>
      super.noSuchMethod(
        Invocation.setter(
          #firestoreInstance,
          _firestoreInstance,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get collection => (super.noSuchMethod(
        Invocation.getter(#collection),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#collection),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#collection),
        ),
      ) as String);

  @override
  _i5.Future<Map<String, dynamic>?> get setUp => (super.noSuchMethod(
        Invocation.getter(#setUp),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<_i3.Article?> getArticleByName({required String? articleTitle}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticleByName,
          [],
          {#articleTitle: articleTitle},
        ),
        returnValue: _i5.Future<_i3.Article?>.value(),
        returnValueForMissingStub: _i5.Future<_i3.Article?>.value(),
      ) as _i5.Future<_i3.Article?>);

  @override
  _i5.Future<_i3.Article?> getArticleOfTheMonth() => (super.noSuchMethod(
        Invocation.method(
          #getArticleOfTheMonth,
          [],
        ),
        returnValue: _i5.Future<_i3.Article?>.value(),
        returnValueForMissingStub: _i5.Future<_i3.Article?>.value(),
      ) as _i5.Future<_i3.Article?>);

  @override
  _i5.Future<_i3.Article?> getHighlighted() => (super.noSuchMethod(
        Invocation.method(
          #getHighlighted,
          [],
        ),
        returnValue: _i5.Future<_i3.Article?>.value(),
        returnValueForMissingStub: _i5.Future<_i3.Article?>.value(),
      ) as _i5.Future<_i3.Article?>);

  @override
  _i5.Future<_i2.DocumentSnapshot<Map<String, dynamic>>> getRawDoc(
          String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRawDoc,
          [path],
        ),
        returnValue:
            _i5.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>.value(
                _FakeDocumentSnapshot_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getRawDoc,
            [path],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>.value(
                _FakeDocumentSnapshot_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getRawDoc,
            [path],
          ),
        )),
      ) as _i5.Future<_i2.DocumentSnapshot<Map<String, dynamic>>>);

  @override
  _i3.Article? buildArticleFromDoc(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildArticleFromDoc,
          [map],
        ),
        returnValueForMissingStub: null,
      ) as _i3.Article?);
}
